export const FETCH_ADMIN_TABLE = 'FETCH_ADMIN_TABLE';
export const FETCH_ADMIN_TABLE_HEADERS = 'FETCH_ADMIN_TABLE_HEADERS';
export const FETCH_ADMIN_TABLE_ROWS = 'FETCH_ADMIN_TABLE_ROWS';
export const FETCH_ADMIN_TABLE_ROW = 'FETCH_ADMIN_TABLE_ROW';
export const NEW_ADMIN_TABLE_ROW = 'NEW_ADMIN_TABLE_ROW';
export const UPDATE_ADMIN_TABLE_ROW = 'UPDATE_ADMIN_TABLE_ROW';
export const DELETE_ADMIN_TABLE_ROW = 'DELETE_ADMIN_TABLE_ROW';