export const FETCH_ADMIN_TABLE = 'REQUEST_FETCH_ADMIN_TABLE';
export const FETCH_ADMIN_TABLE_SUCCESS = `${FETCH_ADMIN_TABLE}_SUCCESS`;
export const FETCH_ADMIN_TABLE_FAIL = `${FETCH_ADMIN_TABLE}_FAIL`;

export const FETCH_ADMIN_TABLE_HEADERS = 'REQUEST_FETCH_ADMIN_TABLE_HEADERS';
export const FETCH_ADMIN_TABLE_HEADERS_SUCCESS = `${FETCH_ADMIN_TABLE_HEADERS}_SUCCESS`;
export const FETCH_ADMIN_TABLE_HEADERS_FAIL = `${FETCH_ADMIN_TABLE_HEADERS}_FAIL`;

export const FETCH_ADMIN_TABLE_ROW = 'REQUEST_FETCH_ADMIN_TABLE_ROW';
export const FETCH_ADMIN_TABLE_ROW_SUCCESS = `${FETCH_ADMIN_TABLE_ROW}_SUCCESS`;
export const FETCH_ADMIN_TABLE_ROW_FAIL = `${FETCH_ADMIN_TABLE_ROW}_FAIL`;


export const FETCH_ADMIN_TABLE_ROWS = 'REQUEST_FETCH_ADMIN_TABLE_ROWS';
export const NEW_ADMIN_TABLE_ROW = 'REQUEST_NEW_ADMIN_TABLE_ROW';
export const UPDATE_ADMIN_TABLE_ROW = 'REQUEST_UPDATE_ADMIN_TABLE_ROW';
export const DELETE_ADMIN_TABLE_ROW = 'REQUEST_DELETE_ADMIN_TABLE_ROW';
