"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.CHANGE_PROPERTY_VALUE = exports.FETCH_PROPERTIES = void 0;
var FETCH_PROPERTIES = 'FETCH_PROPERTIES';
exports.FETCH_PROPERTIES = FETCH_PROPERTIES;
var CHANGE_PROPERTY_VALUE = 'CHANGE_PROPERTY_VALUE';
exports.CHANGE_PROPERTY_VALUE = CHANGE_PROPERTY_VALUE;