"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DELETE_ADMIN_TABLE_ROW = exports.UPDATE_ADMIN_TABLE_ROW = exports.NEW_ADMIN_TABLE_ROW = exports.FETCH_ADMIN_TABLE_ROW = exports.FETCH_ADMIN_TABLE_ROWS = exports.FETCH_ADMIN_TABLE_HEADERS = exports.FETCH_ADMIN_TABLE = void 0;
var FETCH_ADMIN_TABLE = 'FETCH_ADMIN_TABLE';
exports.FETCH_ADMIN_TABLE = FETCH_ADMIN_TABLE;
var FETCH_ADMIN_TABLE_HEADERS = 'FETCH_ADMIN_TABLE_HEADERS';
exports.FETCH_ADMIN_TABLE_HEADERS = FETCH_ADMIN_TABLE_HEADERS;
var FETCH_ADMIN_TABLE_ROWS = 'FETCH_ADMIN_TABLE_ROWS';
exports.FETCH_ADMIN_TABLE_ROWS = FETCH_ADMIN_TABLE_ROWS;
var FETCH_ADMIN_TABLE_ROW = 'FETCH_ADMIN_TABLE_ROW';
exports.FETCH_ADMIN_TABLE_ROW = FETCH_ADMIN_TABLE_ROW;
var NEW_ADMIN_TABLE_ROW = 'NEW_ADMIN_TABLE_ROW';
exports.NEW_ADMIN_TABLE_ROW = NEW_ADMIN_TABLE_ROW;
var UPDATE_ADMIN_TABLE_ROW = 'UPDATE_ADMIN_TABLE_ROW';
exports.UPDATE_ADMIN_TABLE_ROW = UPDATE_ADMIN_TABLE_ROW;
var DELETE_ADMIN_TABLE_ROW = 'DELETE_ADMIN_TABLE_ROW';
exports.DELETE_ADMIN_TABLE_ROW = DELETE_ADMIN_TABLE_ROW;